add solution for 1-module 2-task
js-tasks-ru/jsbasic-20220113_zvykkk pull request #2
Opened 2022-01-20 15:53 UTC by zvykkk

2022-01-20 15:54 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-01-20 16:02 UTC, SinimaWath requested changes

2022-01-20 16:02 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  return ((name != null) && (!name.includes(' ')) && (name.length > 3)) ? true : false;
Тут нет необходимости в тернарном операторе, так как твое выражение и так возвращает true/false

2022-01-21 09:08 UTC, zvykkk commented on 1-module/2-task/index.js
> +  return ((name != null) && (!name.includes(' ')) && (name.length > 3)) ? true : false;
понятно) поправила)

2022-01-21 09:09 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-01-21 09:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-01-21 10:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-01-21 14:22 UTC, SinimaWath approved these changes
все ок!

2022-01-21 14:22 UTC, merged